In [1]:
import pandas as pd
lst_column = ["HHID", "HVIDX", "HV024", "HV025", "HV026","HV104","HV105","HB2","HA2","HA3","HB3","HA13","HVIDX","HV270","SHDIST","HA40","HB40","BMI"]
# df = pd.read_spss("data/IAPR7EFL.SAV")[lst_column]
import pyreadstat
df, meta = pyreadstat.read_sav(
    "data/IAPR7EFL.SAV",
    usecols=lst_column)

In [2]:
df.head()

,HHID,HVIDX,HV024,HV025,HV026,HV270,SHDIST,HV104,HV105,HA2,HA3,HA13,HA40,HB2,HB3,HB40
0,0100101305,1.0,1.0,2.0,NaN,3.0,1.0,1.0,50.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0100101305,2.0,1.0,2.0,NaN,3.0,1.0,2.0,51.0,NaN,NaN,6.0,NaN,NaN,NaN,NaN
2,0100101305,3.0,1.0,2.0,NaN,3.0,1.0,1.0,25.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,0100101305,4.0,1.0,2.0,NaN,3.0,1.0,2.0,22.0,353.0,1427.0,0.0,1734.0,NaN,NaN,NaN
4,0100101305,5.0,1.0,2.0,NaN,3.0,1.0,2.0,19.0,310.0,1397.0,0.0,1586.0,NaN,NaN,NaN

In [3]:
labels=pd.read_csv('data/variables_household_nfhs.csv')

In [4]:
labels.head()

   Unnamed: 0 Column_Name            Column_Label values
0           0        HHID     Case Identification    NaN
1           1       HVIDX             Line number    NaN
2           2       HV000  Country code and phase    NaN
3           3       HV001          Cluster number    NaN
4           4       HV002        Household number    NaN

In [5]:
df.columns

Index(['HHID', 'HVIDX', 'HV024', 'HV025', 'HV026', 'HV270', 'SHDIST', 'HV104',
       'HV105', 'HA2', 'HA3', 'HA13', 'HA40', 'HB2', 'HB3', 'HB40'],
      dtype='object')

In [6]:
for i in df.columns:
    if i in labels['Column_Name'].values:
        print(i)
        if(i=='HB40'):
            df = df.rename(columns={i:"BMI_Man"} )
        elif(i=='HA40'):
            df = df.rename(columns={i:"BMI_Woman"})
        else:
            index=labels[labels['Column_Name']==i].index[0]
            df = df.rename(columns={i: labels['Column_Label'].loc[index]})

HHID
HVIDX
HV024
HV025
HV026
HV270
SHDIST
HV104
HV105
HA2
HA3
HA13
HA40
HB2
HB3
HB40

In [7]:
print(df.columns)

Index(['Case Identification', 'Line number', 'State',
       'Type of place of residence', 'NA - Place of residence',
       'Wealth index combined', 'District number', 'Sex of household member',
       'Age of household members', 'Woman's weight in kilograms (1 decimal)',
       'Woman's height in centimeters (1 decimal)',
       'Result of measurement - height/weight', 'BMI_Woman',
       'Man's weight in kilograms (1 decimal)',
       'Man's height in centimeters (1 decimal)', 'BMI_Man'],
      dtype='object')

In [8]:
df.head()

,Case Identification,Line number,State,Type of place of residence,NA - Place of residence,Wealth index combined,District number,Sex of household member,Age of household members,Woman's weight in kilograms (1 decimal),Woman's height in centimeters (1 decimal),Result of measurement - height/weight,BMI_Woman,Man's weight in kilograms (1 decimal),Man's height in centimeters (1 decimal),BMI_Man
0,0100101305,1.0,1.0,2.0,NaN,3.0,1.0,1.0,50.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0100101305,2.0,1.0,2.0,NaN,3.0,1.0,2.0,51.0,NaN,NaN,6.0,NaN,NaN,NaN,NaN
2,0100101305,3.0,1.0,2.0,NaN,3.0,1.0,1.0,25.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,0100101305,4.0,1.0,2.0,NaN,3.0,1.0,2.0,22.0,353.0,1427.0,0.0,1734.0,NaN,NaN,NaN
4,0100101305,5.0,1.0,2.0,NaN,3.0,1.0,2.0,19.0,310.0,1397.0,0.0,1586.0,NaN,NaN,NaN

In [9]:
type(df["Sex of household member"][0])

numpy.float64

In [10]:
df[df["Sex of household member"]==2.0].isnull().sum()

Case Identification                                0
Line number                                        0
State                                              0
Type of place of residence                         0
NA - Place of residence                      1433580
Wealth index combined                              0
District number                                    0
Sex of household member                            0
Age of household members                           0
Woman's weight in kilograms (1 decimal)       669091
Woman's height in centimeters (1 decimal)     669125
Result of measurement - height/weight         369649
BMI_Woman                                     723420
Man's weight in kilograms (1 decimal)        1433579
Man's height in centimeters (1 decimal)      1433579
BMI_Man                                      1433580
dtype: int64

In [11]:
df["Combined_BMI"]= df['BMI_Woman'].fillna(df['BMI_Man'])
df["Combined_weight"]= df["Woman's weight in kilograms (1 decimal)"].fillna(df["Man's weight in kilograms (1 decimal)"])
df["Combined_height"]= df["Woman's height in centimeters (1 decimal)"].fillna(df["Man's height in centimeters (1 decimal)"])
df.drop(columns=['BMI_Woman','BMI_Man',"Woman's weight in kilograms (1 decimal)","Man's weight in kilograms (1 decimal)",
                 "Woman's height in centimeters (1 decimal)","Man's height in centimeters (1 decimal)","NA - Place of residence"],inplace= True)

In [12]:
df.head(10)

,Case Identification,Line number,State,Type of place of residence,Wealth index combined,District number,Sex of household member,Age of household members,Result of measurement - height/weight,Combined_BMI,Combined_weight,Combined_height
0,0100101305,1.0,1.0,2.0,3.0,1.0,1.0,50.0,NaN,NaN,NaN,NaN
1,0100101305,2.0,1.0,2.0,3.0,1.0,2.0,51.0,6.0,NaN,NaN,NaN
2,0100101305,3.0,1.0,2.0,3.0,1.0,1.0,25.0,NaN,NaN,NaN,NaN
3,0100101305,4.0,1.0,2.0,3.0,1.0,2.0,22.0,0.0,1734.0,353.0,1427.0
4,0100101305,5.0,1.0,2.0,3.0,1.0,2.0,19.0,0.0,1586.0,310.0,1397.0
5,0100101345,1.0,1.0,2.0,3.0,1.0,1.0,42.0,NaN,NaN,NaN,NaN
6,0100101345,2.0,1.0,2.0,3.0,1.0,2.0,38.0,0.0,3449.0,755.0,1479.0
7,0100101345,3.0,1.0,2.0,3.0,1.0,1.0,14.0,NaN,NaN,NaN,NaN
8,0100101345,4.0,1.0,2.0,3.0,1.0,1.0,8.0,NaN,NaN,NaN,NaN
9,0100101383,1.0,1.0,2.0,3.0,1.0,1.0,42.0,NaN,NaN,NaN,NaN

In [17]:
df["Unique_ID"]= df["Case Identification"].astype(str) + "_" + df["Line number"].astype(int).astype(str)

In [18]:
df.head()

,Case Identification,Line number,State,Type of place of residence,Wealth index combined,District number,Sex of household member,Age of household members,Result of measurement - height/weight,Combined_BMI,Combined_weight,Combined_height,Unique_ID
0,0100101305,1.0,1.0,2.0,3.0,1.0,1.0,50.0,NaN,NaN,NaN,NaN,0100101305_1
1,0100101305,2.0,1.0,2.0,3.0,1.0,2.0,51.0,6.0,NaN,NaN,NaN,0100101305_2
2,0100101305,3.0,1.0,2.0,3.0,1.0,1.0,25.0,NaN,NaN,NaN,NaN,0100101305_3
3,0100101305,4.0,1.0,2.0,3.0,1.0,2.0,22.0,0.0,1734.0,353.0,1427.0,0100101305_4
4,0100101305,5.0,1.0,2.0,3.0,1.0,2.0,19.0,0.0,1586.0,310.0,1397.0,0100101305_5

In [20]:
df.drop(columns=["Case Identification","Line number","Result of measurement - height/weight"],inplace= True)

In [21]:
df.head()

,State,Type of place of residence,Wealth index combined,District number,Sex of household member,Age of household members,Combined_BMI,Combined_weight,Combined_height,Unique_ID
0,1.0,2.0,3.0,1.0,1.0,50.0,NaN,NaN,NaN,0100101305_1
1,1.0,2.0,3.0,1.0,2.0,51.0,NaN,NaN,NaN,0100101305_2
2,1.0,2.0,3.0,1.0,1.0,25.0,NaN,NaN,NaN,0100101305_3
3,1.0,2.0,3.0,1.0,2.0,22.0,1734.0,353.0,1427.0,0100101305_4
4,1.0,2.0,3.0,1.0,2.0,19.0,1586.0,310.0,1397.0,0100101305_5

In [22]:
df.columns

Index(['State', 'Type of place of residence', 'Wealth index combined',
       'District number', 'Sex of household member',
       'Age of household members', 'Combined_BMI', 'Combined_weight',
       'Combined_height', 'Unique_ID'],
      dtype='object')

In [48]:
df_copy= df[['Unique_ID','Sex of household member','State', 'Type of place of residence', 'Wealth index combined',
       'District number',
       'Age of household members', 'Combined_weight',
       'Combined_height','Combined_BMI']]

In [49]:
df_copy.head()

,Unique_ID,Sex of household member,State,Type of place of residence,Wealth index combined,District number,Age of household members,Combined_weight,Combined_height,Combined_BMI
0,0100101305_1,1.0,1.0,2.0,3.0,1.0,50.0,NaN,NaN,NaN
1,0100101305_2,2.0,1.0,2.0,3.0,1.0,51.0,NaN,NaN,NaN
2,0100101305_3,1.0,1.0,2.0,3.0,1.0,25.0,NaN,NaN,NaN
3,0100101305_4,2.0,1.0,2.0,3.0,1.0,22.0,353.0,1427.0,1734.0
4,0100101305_5,2.0,1.0,2.0,3.0,1.0,19.0,310.0,1397.0,1586.0

In [50]:
df_copy.isnull().sum()

Unique_ID                           0
Sex of household member             0
State                               0
Type of place of residence          0
Wealth index combined               0
District number                     0
Age of household members            0
Combined_weight               1954982
Combined_height               1955018
Combined_BMI                  2035541
dtype: int64

In [51]:
df_copy=df_copy.dropna(subset=["Combined_weight","Combined_height","Combined_BMI"],how="all")

In [52]:
df_copy.isnull().sum()

Unique_ID                         0
Sex of household member           0
State                             0
Type of place of residence        0
Wealth index combined             0
District number                   0
Age of household members          0
Combined_weight                 158
Combined_height                 194
Combined_BMI                  80717
dtype: int64

In [53]:
df_copy["Combined_weight"]=df_copy["Combined_weight"]/10
df_copy["Combined_height"]=df_copy["Combined_height"]/10
df_copy["Combined_BMI"]=df_copy["Combined_BMI"]/100

In [54]:
df_copy.head()

,Unique_ID,Sex of household member,State,Type of place of residence,Wealth index combined,District number,Age of household members,Combined_weight,Combined_height,Combined_BMI
3,0100101305_4,2.0,1.0,2.0,3.0,1.0,22.0,35.3,142.7,17.34
4,0100101305_5,2.0,1.0,2.0,3.0,1.0,19.0,31.0,139.7,15.86
6,0100101345_2,2.0,1.0,2.0,3.0,1.0,38.0,75.5,147.9,34.49
10,0100101383_2,2.0,1.0,2.0,3.0,1.0,40.0,70.8,162.7,26.73
11,0100101383_3,2.0,1.0,2.0,3.0,1.0,22.0,35.8,152.7,15.33

In [55]:
df_copy[df_copy['Combined_weight'].isna()]

,Unique_ID,Sex of household member,State,Type of place of residence,Wealth index combined,District number,Age of household members,Combined_weight,Combined_height,Combined_BMI
6471,0100203238_1,2.0,1.0,2.0,2.0,2.0,58.0,NaN,NaN,20.63
40280,0101103411_1,1.0,1.0,1.0,4.0,11.0,54.0,NaN,NaN,27.99
139139,0303803157_2,2.0,3.0,2.0,4.0,38.0,49.0,NaN,NaN,35.03
151308,0304102159_2,2.0,3.0,2.0,5.0,41.0,46.0,NaN,999.5,NaN
154460,0304200626_5,2.0,3.0,2.0,2.0,42.0,19.0,NaN,999.6,NaN
...,...,...,...,...,...,...,...,...,...,...
2759803,3689001914_1,2.0,36.0,2.0,3.0,890.0,55.0,NaN,NaN,21.88
2784361,3689802150_2,2.0,36.0,1.0,5.0,898.0,49.0,NaN,NaN,36.38
2814676,3690702377_2,2.0,36.0,2.0,3.0,907.0,53.0,NaN,NaN,29.15
2815509,3690703674_4,2.0,36.0,1.0,5.0,907.0,53.0,NaN,NaN,26.41
2821042,3690902477_2,2.0,36.0,2.0,3.0,909.0,76.0,NaN,NaN,18.61

In [56]:
df_copy[df_copy['Combined_BMI'].isnull()][df_copy["Combined_weight"].between(20,200) & df_copy["Combined_height"].between(50,220)].shape

C:\Users\vishw\AppData\Local\Temp\ipykernel_3652\1294418922.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df_copy[df_copy['Combined_BMI'].isnull()][df_copy["Combined_weight"].between(20,200) & df_copy["Combined_height"].between(50,220)].shape

(0, 10)

In [57]:
df_copy[~df_copy['Combined_BMI'].isnull()].shape

(808376, 10)

In [58]:
df_copy[df_copy["Combined_weight"].between(20,200) & df_copy["Combined_height"].between(50,220)].shape

(808169, 10)

In [59]:
df_copy=df_copy.dropna(subset=['Combined_BMI']).drop(columns=['Combined_weight','Combined_height'])

In [60]:
df_copy.isnull().sum()

Unique_ID                     0
Sex of household member       0
State                         0
Type of place of residence    0
Wealth index combined         0
District number               0
Age of household members      0
Combined_BMI                  0
dtype: int64

In [61]:
df_copy.shape

(808376, 8)

In [63]:
df_copy[df_copy['Sex of household member']==2.0].shape

(710160, 8)

In [65]:
# df_copy.to_csv('data/cleaned_data.csv')

In [1]:
import pandas as pd